---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp XCPのドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/releasenotes.html"
  - title: XCP を使い始める
    entries:
    - title: XCP の詳細をご確認ください
      url: "/xcp-index.html"
    - title: XCP NFS アドオン機能
      url: "/xcp-nfs-add-ons.html"
    - title: サポートされない機能です
      url: "/xcp-unsupported-features.html"
    - title: サポートされている構成
      url: "/xcp-supported-configurations.html"
    - title: XCP で使用されるポート
      url: "/xcp-ports-used.html"
  - title: XCP をインストール
    entries:
    - title: XCPのインストールを準備します
      url: "/xcp-install-xcp.html"
    - title: XCP NFS 用 Linux を準備します
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: XCP SMB 用に Windows を準備します
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: ファイル分析を準備
      url: "/xcp-prepare-file-analytics.html"
    - title: XCP NFS をインストールします
      url: "/xcp-install-xcp-nfs.html"
    - title: XCP SMB をインストールします
      url: "/xcp-install-xcp-smb.html"
    - title: File Analytics for NFS をインストールします
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: SMB 向けファイル分析をインストール
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: XCP を設定します
    entries:
    - title: XCP NFS の INI ファイルを設定します
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: パフォーマンスの調整
      url: "/xcp-performance-tuning.html"
    - title: 環境変数
      url: "/xcp-environment-variable.html"
    - title: POSIX コネクタを設定します
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: HDFS コネクタを設定します
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: マルチノードスケールアウトを構成します
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: S3 Connectorを設定します
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: データ移行を計画
    entries:
    - title: 概要
      url: "/xcp-plan-data-migration.html"
    - title: NFS データ移行を計画
      url: "/xcp-plan-nfs-data-migration.html"
    - title: SMB データ移行を計画
      url: "/xcp-plan-smb-data-migration.html"
    - title: HDFSデータ移行を計画
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: File Analytics の使用を計画する
      entries:
      - title: データ移行の計画
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: File Analytics にアクセスします
        url: "/xcp-access-file-analytics.html"
      - title: ファイルサーバを追加します
        url: "/xcp-add-file-servers.html"
      - title: スキャンを実行します
        url: "/xcp-run-a-scan.html"
    - title: フィルタ
      url: "/xcp-filters.html"
    - title: NFS および SMB のロギング（オプション）
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: データを移行
    entries:
    - title: NFS データを移行する
      url: "/xcp-migrate-data.html"
    - title: SMB データを移行
      url: "/xcp-migrate-smb-data.html"
    - title: SMBノNTFSタイタイタイテエタストリイムノイコウ
      entries:
      - title: SMBノNTFSタイタイタイテエタストリイムノイコウ
        url: "/xcp-smb-ads.html"
    - title: HDFSデータを移行
      url: "/xcp-migrate-hdfs-data.html"
    - title: 同じホストで複数のXCPジョブを実行します
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: その他の NFS 機能
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: トラブルシューティングを行う
    entries:
    - title: XCP NFS エラーのトラブルシューティング
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: XCP SMBエラーのトラブルシューティング
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: XCP File Analytics エラーのトラブルシューティング
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: XCPリファレンス
    entries:
    - title: XCPコマンドリファレンスの概要
      url: "/xcp-reference-overview.html"
    - title: NFSコマンドリファレンス
      entries:
      - title: ヘルプ
        url: "/xcp-nfs-reference-help.html"
      - title: 表示
        url: "/xcp-nfs-reference-show.html"
      - title: 使用許諾
        url: "/xcp-nfs-reference-license.html"
      - title: アクティブにします
        url: "/xcp-nfs-reference-activate.html"
      - title: スキャン
        url: "/xcp-nfs-reference-scan.html"
      - title: コピー
        url: "/xcp-nfs-reference-copy.html"
      - title: 同期
        url: "/xcp-nfs-reference-sync.html"
      - title: 再開
        url: "/xcp-nfs-reference-resume.html"
      - title: 検証
        url: "/xcp-nfs-reference-verify.html"
      - title: chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: chown
        url: "/xcp-nfs-reference-chown.html"
      - title: ログダンプ
        url: "/xcp-nfs-reference-logdump.html"
      - title: 削除
        url: "/xcp-nfs-reference-delete.html"
      - title: 概算見積書
        url: "/xcp-nfs-reference-estimate.html"
      - title: インデックス削除
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: iSync
        url: "/xcp-nfs-reference-isync.html"
    - title: SMBコマンドリファレンス
      entries:
      - title: ヘルプ
        url: "/xcp-smb-reference-help.html"
      - title: 表示
        url: "/xcp-smb-reference-show.html"
      - title: 使用許諾
        url: "/xcp-smb-reference-license.html"
      - title: アクティブにします
        url: "/xcp-smb-reference-activate.html"
      - title: スキャン
        url: "/xcp-smb-reference-scan.html"
      - title: コピー
        url: "/xcp-smb-reference-copy.html"
      - title: 同期
        url: "/xcp-smb-reference-sync.html"
      - title: 検証
        url: "/xcp-smb-reference-verify.html"
      - title: 設定
        url: "/xcp-smb-reference-configure.html"
      - title: リスン
        url: "/xcp-smb-reference-listen.html"
    - title: XCPのユースケース
      entries:
      - title: XCPのユースケース
        url: "/xcp-reference-use-cases.html"
    - title: XCPロギング
      entries:
      - title: logconfigオプションを設定します。
        url: "/xcp-reference-logging-logconfig.html"
      - title: eventlogオプションを設定する
        url: "/xcp-reference-logging-eventlog.html"
      - title: syslogクライアントを有効にする
        url: "/xcp-reference-logging-syslog.html"
    - title: XCPイベントログ
      entries:
      - title: NFSイベントログ
        url: "/xcp-reference-event-logs-nfs.html"
      - title: SMBイヘントロク
        url: "/xcp-reference-event-logs-smb.html"
  - title: 法的通知
    url: "/legal-notices.html"
