---
sidebar: sidebar 
permalink: xcp-nfs-reference-chown.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFSコマンドリファレンス 
---
= chown
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS `chown` コマンドは、指定したディレクトリ構造のすべてのファイルの所有権をスキャンして変更します。。 `chown` コマンドには、NFS共有またはPOSIXパスを変数として指定する必要があります。xcp chownは、指定されたパスの所有権を再帰的に変更します。。 `chown` コマンドは、ファイルの変更されたユーザID（UID）を表示します。

.構文
[source, cli]
----
xcp chown -user/-group <user-name/group-name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user user2 -v 101.101.10.110:/s_v1/smaple_set/D1

Sat Apr 2 23:06:05 2022
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1 from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/1.txt from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/softlink_1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/hardlink_1.img from 1001:0 to 1004:0
changed ownership of 101.101.10.110:/s_v1/smaple_set/D1/softlink_to_hardlink_1.img from 1001:0 to
1004:0
Xcp command : xcp chown -user user2 -v 101.101.10.110:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (1.82 KiB/s), 1.11 KiB out (923/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====
次の表に、を示します `chown` パラメータとその概要。

[cols="2*"]
|===
| パラメータ | 説明 


| <<nfs_chown_exclude,chown-exclude filter>   | フィルタに一致するファイルとディレクトリを除外します。 


| <<nfs_chown_match,chown-match filter>   | フィルタに一致するファイルとディレクトリのみを処理します。 


| <<nfs_chown_group,chown-group group>   | ソースでLinuxグループID（GID）を設定します。 


| <<nfs_chown_user,chown-user user>  | ソースでLinux UIDを設定します。 


| <<nfs_chown_user_from,chown-user-from user_from>  | UIDを変更します。 


| <<nfs_chown_group_from,chown-group-from group_from>   | GIDを変更します。 


| <<nfs_chown_reference,chown-reference reference>  | 参照されるファイルまたはディレクトリポイントを指定します。 


| <<nfs_chown_v,chown-v >> | 処理されたすべてのオブジェクトの出力を報告します。 
|===


== chown-exclude <filter>

を使用します `-exclude <filter>` パラメータと `chown` フィルタに一致するファイルとディレクトリを除外するコマンド。

.構文
[source, cli]
----
xcp chown -exclude <filter> -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -exclude "fnm('1.img')" -user user2 101.101.10.210:/s_v1/smaple_set/D1

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chown -exclude fnm('1.img') -user user2101.101.10.210:/s_v1/smaple_set/D1
Stats : 5 scanned, 1 excluded, 5 changed ownership
Speed : 2.10 KiB in (1.75 KiB/s), 976 out (812/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-match <filter>

を使用します `-match <filter>` パラメータと `chown` フィルタに一致するファイルとディレクトリのみを処理するコマンド。

.構文
[source, cli]
----
xcp chown -match <filter>  -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -exclude "fnm('1.img')" -user user2 101.101.10.210:/s_v1/smaple_set/D1

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chown -exclude fnm('1.img') -user user2101.101.10.210:/s_v1/smaple_set/D1
Stats : 5 scanned, 1 excluded, 5 changed ownership
Speed : 2.10 KiB in (1.75 KiB/s), 976 out (812/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-group <group>

を使用します `-group <group>` パラメータと `chown` ソースでLinux GIDを設定するコマンド。

.構文
[source, cli]
----
xcp chown -match <filter> -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -group group1 101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -group group1 101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (1.92 KiB/s), 1.11 KiB out (974/s)
Total Time : 1s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-user <user>

を使用します `-user <user>` パラメータと `chown` ソースでLinux UIDを設定するコマンド。

.構文
[source, cli]
----
xcp chown -user -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user user1 102.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -user user1 102.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (3.12 KiB/s), 1.11 KiB out (1.55 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-user -<user_from>から

を使用します `-user-from <user_from>` パラメータと `chown` UIDを変更するコマンド。

.構文
[source, cli]
----
xcp chown -user-from user1 -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user-from user1 -user user2
101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -user-from user1 -user user2 102.108.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (2.44 KiB/s), 1.11 KiB out (1.21 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-group -<group_from>から

を使用します `-group-from <group_from>` パラメータと `chown` GIDを変更するコマンド。

.構文
[source, cli]
----
xcp chown -group-from <group_name> -group <group_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -group-from group1 -group group2
101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -group-from group1 -group group2
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (4.99 KiB/s), 1.11 KiB out (2.47 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-reference <reference>

を使用します `-reference <reference>` パラメータと `chown` コマンドを使用して、参照されるファイルまたはディレクトリポイントを指定します。

.構文
[source, cli]
----
xcp chown -reference <reference> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -reference 101.101.10.210:/s_v1/smaple_set/D2/2.img 101.101.10.210:/s_v1/smaple_set/D1

Xcp command : xcp chown -reference 101.101.10.210:/s_v1/smaple_set/D2/2.img
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 3.11 KiB in (6.25 KiB/s), 2.01 KiB out (4.05 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chown-v

を使用します `-v` パラメータと `chown` 処理されたすべてのオブジェクトの出力をレポートするコマンド。

.構文
[source, cli]
----
xcp chown -user-from <user_name> -v -user <user_name> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chown -user-from user2 -v -user user1
101.101.10.210:/s_v1/smaple_set/D1

changed ownership of 101.101.10.210:/s_v1/smaple_set/D1 from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/1.img from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/1.txt from 1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/softlink_1.img from 1004:1003 to
1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/softlink_to_hardlink_1.img from
1004:1003 to 1001:1003
changed ownership of 101.101.10.210:/s_v1/smaple_set/D1/hardlink_1.img from 1004:1003 to
1001:1003
Xcp command : xcp chown -user-from user2 -v -user user1
101.101.10.210:/s_v1/smaple_set/D1
Stats : 6 scanned, 6 changed ownership
Speed : 2.25 KiB in (2.02 KiB/s), 1.11 KiB out (1.00 KiB/s)
Total Time : 1s.

STATUS : PASSED
[root@user-1]
----
====