---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: データを移行 
---
= NFS データを移行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
を使用して移行を計画したら `show` および `scan` コマンドを実行すると、NFSデータを移行できます。



== コピー

copy コマンドは ' ソース・ディレクトリ構造全体をスキャンして ' デスティネーションの NFSv3 エクスポートにコピーします'copy' コマンドでは ' ソース・パスとデスティネーション・パスを変数として指定する必要がありますコピー処理の終了時に、スキャンおよびコピーされたファイル、スループット / 速度、および経過時間の詳細が表示されます

* 例： *

[listing]
----
xcp copy -newid <id> src_server:/src_export dst_server:/dst_export
----
* POSIX パスの例 :*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
を実行します `xcp help copy` 詳細：



== 再開

「 resume 」コマンドは、カタログインデックス名または番号を指定することにより、以前に中断されたコピー操作を再開します。カタログインデックスの名前または以前のコピー操作の番号は '<catalog path>:/catalog/indexs' ディレクトリに保存されます

* 例： *

[listing]
----
xcp resume [options] -id <id used for copy>
----
を実行します `xcp help resume` 詳細：



== 同期

'sync' コマンドは ' カタログ・インデックス・タグ名または以前のコピー操作の番号を使用して ' ソース NFS ディレクトリで実行された変更および変更をスキャンしますソースの差分変更がコピーされ、ターゲットディレクトリに適用されます。古いカタログインデックス番号は、 sync 操作 # の後に新しい 1 つ [.underline] # で置き換えられます。

* 例： *

[listing]
----
xcp sync [options] -id <id used for copy>
----
を実行します `xcp help sync` 詳細：



== 確認します

「 ve rify 」コマンドでは、カタログインデックス番号を使用せずにコピー操作を行った後に、ソースディレクトリとターゲットディレクトリ間でのバイト単位のデータ比較を完全に使用します。コマンドは、権限を含む、変更日時およびその他のファイルまたはディレクトリの属性をチェックします。また、両側のファイルを読み取り、データを比較します。

* 例： *

[listing]
----
xcp verify src_server:/src_export dst_server:/dst_export
----
* POSIX パスの例 :*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
を実行します `xcp help verify` 詳細：



== iSync

。 `isync` コマンドは、ソースとデスティネーションを比較し、カタログインデックスを使用せずにターゲットの差分を同期します。

* 例 *

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
を使用できます `isync` を使用 `estimate` の所要時間を見積もるオプション `isync` 増分変更を同期するコマンド。。 `-id` パラメータは、前回のコピー処理のカタログ名を指定します。


NOTE: 使用されているデータセットサイズの25%以上を変更すると、 `isync estimate` コマンドで想定した結果が表示されない場合があります。

* 例 *

[listing]
----
xcp isync estimate -id <name>
----
を実行します `xcp help isync` 詳細：
