---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: File Analytics for NFS をインストールまたはアップグレードします 
---
= File Analytics for NFS をインストールします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
File Analytics for NFS をインストールまたはアップグレードします。

.このタスクについて
NFSのシステム要件については、を参照してください。 link:xcp-install-xcp-nfs.html["XCP NFS をインストールします"]。

。 `configure.sh` スクリプトは、Red Hat Enterprise Linux（RHEL）ホストマシンにXCP File Analyticsをインストールします。インストールの一環として、Postgres Database、Apache HTTPDサーバ、およびその他の必要なパッケージがホストLinuxマシンにインストールされます。サポートされている特定のRHELバージョンについては、を参照してください。 link:https://mysupport.netapp.com/matrix/["IMT"^]。必要に応じて、より新しいバージョンに変更または更新したり、セキュリティガイドラインに従って更新したりできます。詳細については、 `configure.sh` スクリプト、実行 `./configure.sh -h` コマンドラインで実行します。

.作業を開始する前に
* 実行中のXCP処理がある場合はNetApp、設定を開始する前に処理を完了することを推奨します。
* Linux マシンが Yum リポジトリサーバまたはインターネットに接続されている必要があります。
* Linuxマシンでファイアウォールが設定されている場合は、ファイアウォールの設定を変更して、XCPサービスで使用されるポート5030を有効にする必要があります。


.手順
. File Analytics for NFS をインストールまたはアップグレードします。
+
[role="tabbed-block"]
====
.File Analyticsをインストール
--
.. に移動します `xcp` フォルダを作成し、 `./configure.sh` スクリプト：
+
インストールが正常に完了すると、次のメッセージが表示されます。

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: このユーザー名とパスワードを使用して、File Analytics GUIにログインできます。



--
.ファイル分析をアップグレード
--
.. に移動します `xcp` フォルダと実行 `./configure.sh -f`。
.. プロンプトで、と入力します `y` システムをクリーンアップして再設定します。
+
スクリプトが承認されると、既存の設定がクリーンアップされ、システムが再構成されます。

+
成功すると、次のメッセージが表示されます。

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. サポートされているブラウザでファイル分析を起動します。* Linuxの\https://<ipアドレス>/XCP *。
+
を参照してください link:xcp-install-xcp-nfs.html["XCP NFS をインストールします"] サポートされるブラウザについては、を参照してください。


