---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: File Analytics for SMB をインストールまたはアップグレードします 
---
= SMB 向けファイル分析をインストール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
File Analytics for SMB をインストールまたはアップグレードします。

.このタスクについて
SMB のシステム要件については、を参照してください link:xcp-install-xcp-smb.html["XCP SMB をインストールします"]。

.作業を開始する前に
* XCP SMB サービスを使用するには、 Linux マシンで NFS 用に XCP File Analytics を設定する必要があります。
* Windows マシンで XCP File Analytics の構成を開始する前に、 Linux マシンで XCP サービスが実行されていることを確認します。




== SMB 向けファイル分析の新規インストール

SMB 向けファイル分析の新規インストールを実行するには、次の手順を実行します。

.手順
. をコピーします `xcp.exe` ファイルをWindowsに保存 `C:` ドライブ。このバイナリは `/xcp/windows` ツールを展開した後、 `tgz` ファイル。
. から XCP ライセンスファイルをダウンロードします link:https://xcp.netapp.com/["XCP サイト"^]。
. C:\NetApp\XCP というフォルダを作成し、 XCP ライセンスをこの場所にコピーします。
. コマンドプロンプトで次のコマンドを使用して、 XCP ライセンスをアクティブにします。 xcp.exe activate
. Windows CLI のコマンドプロンプトで、「 XCP configure 」を実行します。
. プロンプトが表示されたら、 XCP File Analytics サーバが設定されている Linux マシンの IP アドレスを入力します。
. をコピーします `server.key` および `server.crt` ファイル `/opt/NetApp/xFiles/xcp/` （XCP File Analyticsがすでに設定されているLinuxボックスで） `C:\NetApp\XCP`。
+
必要に応じて、CA証明書がある場合は、 `C:\NetApp\XCP` 同じ名前と拡張子を持つ。

. Windowsマシンに移動し、 `xcp listen`では、XCP File Analytics for SMBの設定が完了しました。サービスを継続的に実行するには、ウィンドウを開いたままにします。
. サポートされているブラウザでFile Analyticsを起動します。 `\https://<ip address of linux>/xcp`
+
を参照してください link:xcp-install-xcp-smb.html["XCP SMB をインストールします"] サポートされるブラウザについては、を参照してください。

. 選択するオプション `OK` ダイアログボックスが表示されたとき。
+

NOTE: 新しいタブが開きます。ブロックされている場合は、ブラウザのポップアップを有効にします。

. URLのプライバシーポリシーに同意します。次のメッセージが表示されます。 `SMB agent is ready to use. Please refresh the analytics page`
. XCP File Analytics GUIをホストする元のタブに戻り、ページを更新して、[Agents]カードの下にSMBエージェントを表示します。




== SMB 向けファイル分析のアップグレード

SMB 向けの既存の File Analytics をアップグレードするには、次の手順を実行します。

. File Analyticsを実行する前に、File Analyticsが実行されているLinuxサーバもアップグレードされていること、およびサービスが実行されていることを確認します。
. Windows では、コマンドラインに「 CTRL-C 」と入力して、既存の XCP サービスを停止します。
. 交換してください `xcp.exe` 最新のバイナリで。
. Windowsマシンに移動し、 `xcp listen` XCP File Analytics for SMBを構成するには、次の手順に従います。サービスを継続的に実行するには、ウィンドウを開いたままにします。
. サポートされているブラウザでFile Analyticsを起動します。 `\https://<ip address of linux>/xcp`
+
を参照してください link:xcp-install-xcp-smb.html["XCP SMB をインストールします"] サポートされるブラウザについては、を参照してください。

. ダイアログボックスが表示されたら、* OK *を選択します。
+

NOTE: 新しいタブが開きます。ブロックされている場合は、ブラウザのポップアップを有効にします。

. URLのプライバシーポリシーに同意します。次のメッセージが表示されます。 `SMB agent is ready to use. Please refresh the analytics page`
. XCP File Analytics GUIをホストする元のタブに戻り、ページを更新して、[Agents]カードの下にSMBエージェントを表示します。

