---
sidebar: sidebar 
permalink: xcp-nfs-reference-estimate.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFSコマンドリファレンス 
---
= 概算見積書
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS `estimate` コマンドを使用すると、ソースからデスティネーションへのベースラインコピーの所要時間を見積もることができます。CPU、RAM、ネットワーク、その他のパラメータなど、現在使用可能なすべてのシステムリソースを使用して、ベースラインコピーが完了するまでの推定時間が計算されます。を使用できます `-target` サンプルコピー処理を開始して推定時間を取得するオプション。

.構文
[source, cli]
----
xcp estimate -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.10.10:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.10.10:/temp4' to
'10.101.10.10:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.10:/temp8' based on a 1m40s live test:
5.3s
Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.10:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====
次の表に、を示します `estimate` パラメータとその概要。

[cols="2*"]
|===
| パラメータ | 説明 


| <<nfs_estimate_id,estimate-id  name >   | 前回のコピーまたはスキャンインデックスのカタログ名を指定します。 


| <<nfs_estimate_gbit,概算見積書-ギガビット  >> | 帯域幅のギガビットを使用して、ベストケース時間を推定します（デフォルト：1）。 


| <<nfs_estimate_target,estimate-target  >> | ライブテストコピーに使用するターゲットを指定します。 


| <<nfs_estimate_t,概算見積書-t/s /m/h]>  | ライブテストコピーの期間を指定します（デフォルト：5m）。 


| <<nfs_estimate_bs,概算見積書- bs[k]>  | 読み取り/書き込みブロックサイズを指定します（デフォルト：64k）。 


| <<nfs_estimate_dircount,estimate-dircount[k]>   | ディレクトリを読み取るための要求サイズを指定します（デフォルト：64k）。 


| <<nfs_estimate_preserveatime,estimate-preserve-atime >> | ファイルまたはディレクトリのアクセス時間を保持します（デフォルト：False）。 


| <<nfs_estimate_loglevel,estimate-loglevel name >  | ログレベルを設定します。使用可能なレベルはINFO、DEBUGです（デフォルト：INFO）。 
|===


== 概算見積書ID <name>

を使用します `-id <name>` パラメータと `estimate` フィルタに一致するファイルとディレクトリを除外するコマンド。

.構文
[source, cli]
----
xcp estimate -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
Job ID: Job_2023-04-20_12.59.31.260914_estimate
== Best-case estimate to copy ‘data-set:/user1given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id csdata01
Estimated Time : 10d13h
Job ID : Job_2023-04-20_12.59.31.260914_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_12.59.31.260914_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
[root@client1 linux]#
----
====


== 見積もり-ギガビット<n>

を使用します `-gbit <n>` パラメータと `estimate` ベストケース時間を推定するコマンド（デフォルト：1）。このオプションは、 `-target` オプション

.構文
[source, cli]
----
xcp estimate -gbit <n> -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -gbit 10 -id estimate01

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.12.28.453735_estimate
== Best-case estimate to copy '10.101.12.11:/temp4' given 10 gigabits of bandwidth ==
0 of data at max 1.25 GiB/s: at least 0.0s
Xcp command : xcp estimate -gbit 10 -id estimate01
Estimated Time : 0.0s
Job ID : Job_2023-04-12_08.12.28.453735_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.12.28.453735_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== 概算見積書-目標<path>

を使用します `-target <path>` パラメータと `estimate` ライブテストコピーに使用するターゲットを指定するコマンド。

.構文
[source, cli]
----
xcp estimate -t 100 -id <name> -target <path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to '10.101.12.11:/temp8'...
estimate regular file copy task completed before the 1m40s duration
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== 概算見積書-t <n[s|m|h]>

を使用します `-t <n[s|m|h]>` パラメータと `estimate` コマンドを使用して、ライブテストコピーの期間を指定します。デフォルト値は5mです。

.構文
[source, cli]
----
xcp estimate -t <n[s|m|h]> -id <name> -target <path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.12:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to
'10.101.12.12:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.12:/temp8' based on a 1m40s live
test: 5.3s

Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== 概算見積書- BS <n[k]>

を使用します `-bs <n[k]>` パラメータと `estimate` 読み取り/書き込みブロックサイズを指定するコマンド。デフォルト値は64kです。

.構文
[source, cli]
----
xcp estimate -id <name> -bs <n[k]>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id estimate01 -bs 128k

xcp: WARNING: your license will expire in less than 7 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-24_08.44.12.564441_estimate
63.2 KiB in (12.5 KiB/s), 2.38 KiB out (484/s), 5s
== Best-case estimate to copy 'xxx' given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id estimate01 -bs 128k
Estimated Time : 10d13h
Job ID : Job_2023-04-24_08.44.12.564441_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-24_08.44.12.564441_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estimate-dircount <n[k]>

を使用します `-dircount <n[k]>` パラメータと `estimate` ディレクトリを読み取るために要求されたサイズを指定するコマンド。デフォルト値は64kです。

.構文
[source, cli]
----
xcp estimate -id <name> -dircount <n[k]> -t <n> -target <path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01 -dircount 128k -t 300 -target <path>

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
Job ID: Job_2023-04-20_13.03.46.820673_estimate
Starting live test for 5m0s to estimate time to copy ‘data-set:/user1 to `<path>`...
1,909 scanned, 126 copied, 2 giants, 580 MiB in (115 MiB/s), 451 MiB out (89.5 MiB/s), 5s
1,909 scanned, 134 copied, 2 giants, 1.23 GiB in (136 MiB/s), 1015 MiB out (112 MiB/s), 10s
1,909 scanned, 143 copied, 2 giants, 1.88 GiB in (131 MiB/s), 1.54 GiB out (113 MiB/s), 15s
.
.
.
7,136 scanned, 2,140 copied, 4 linked, 8 giants, 33.6 GiB in (110 MiB/s), 32.4 GiB out (110
MiB/s), 4m57s
Sample test copy completed for, 300.03s
0 in (-7215675436.180/s), 0 out (-6951487617.036/s), 5m2s
2,186 scanned, 610 KiB in (121 KiB/s), 76.9 KiB out (15.3 KiB/s), 5m7s
Estimated time to copy ‘data-set:/user1to '10.01.12.11:/mapr11' based on a 5m0s live test:
7d6h
Xcp command : xcp estimate -id csdata01 -dircount 128k -t 300 -target 10.101.12.11:/mapr11
Estimated Time : 7d6h
Job ID : Job_2023-04-20_13.03.46.820673_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_13.03.46.820673_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
[root@client1 linux]#
----
====


== 概算見積書-パラレル<n>

を使用します `-parallel <n>` パラメータと `estimate` コマンドを使用して、同時バッチプロセスの最大数を指定します。デフォルト値は7です。

.構文
[source, cli]
----
xcp estimate -loglevel <name> -parallel <n> -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== estimate-preserve-atime

を使用します `-preserve-atime` パラメータと `estimate` コマンドを使用して、ファイルまたはディレクトリのアクセス時間を保持します。デフォルト値は false です。

.構文
[source, cli]
----
xcp estimate -loglevel <name> -preserve-atime -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp estimate -loglevel DEBUG -preserve-atime -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.19.04.050516_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth
==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -preserve-atime -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.19.04.050516_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.19.04.050516_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== 概算見積書-ログレベルの<name>

を使用します `-loglevel <name>` パラメータと `estimate` ログレベルを設定するコマンド。使用可能なレベルはINFOおよびDEBUGです。デフォルトのレベルは「情報」です。

.構文
[source, cli]
----
xcp estimate -loglevel <name> -id <name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====