---
sidebar: sidebar 
permalink: xcp-prepare-linux-for-xcp-nfs.html 
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage, 
summary: XCP NFS 用 Linux を準備します 
---
= XCP NFS 用 Linux を準備します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS は、 Linux クライアントホストシステムを使用して並列 I/O ストリームを生成し、使用可能なネットワークとストレージのパフォーマンスを最大限に活用します。

root ユーザと root 以外のユーザに対して設定を行ったあと、設定に応じてどちらかのユーザを選択できます。



== カタログを構成します

XCP は、 NFSv3 からアクセス可能なカタログディレクトリまたは必要な権限を持つすべての POSIX パスに処理レポートとメタデータを保存します。

* カタログのプロビジョニングは、インストール前の 1 回限りの作業です。
* 1 、 000 万個のオブジェクト（ディレクトリ、ファイル、ハードリンク）ごとに約 1GB のスペースがインデックス化されます。再開または同期可能な各コピーと、オフラインで検索可能な各スキャンにはインデックスが必要です。
* パフォーマンスをサポートするには、エクスポートディレクトリを含むアグリゲートに少なくとも 10 本のディスクまたは SSD が必要です。



NOTE: XCP カタログは別途保存する必要があります。ソースまたはデスティネーションの NFS エクスポートディレクトリに配置されていない。XCP はメタデータを維持します。メタデータは、初期セットアップで指定したカタログ上の場所にあるレポートです。XCP を使用して処理を実行する前に、レポートの保存先を指定して更新する必要があります。



== ストレージを設定する

XCP NFS の移行および移行には、ソースとターゲットのストレージに関する次の要件があります。

* ソースサーバとターゲットサーバで、 NFSv3 または NFS v4.0 プロトコルサービスを有効にしている必要があります
+
** NFSv4 ACL を移行する場合は、デスティネーションサーバで NFSv4 プロトコルサービスと NFSv4 ACL を有効にする必要があります。


* ソースボリュームとターゲットボリュームは、 XCP Linux クライアントホストへの「 root 」アクセスでエクスポートされる必要があります。
* NFSv4 ACL を移行するには、 ACL の移行が必要なボリュームにエンコード言語 UTF-8 を使用する必要があります。


[NOTE]
====
* 管理者が誤ってソースボリュームを変更しないようにするには、 NFSv3 および NFSv4 エクスポートディレクトリのソースボリュームを読み取り専用として設定する必要があります。
* ONTAP では、 diagnostic 「 -atime-update 」オプションを使用して atime を保持できます。この機能は ONTAP でのみ使用でき、 XCP の実行中にソースオブジェクトで atime を保持する場合に便利です。


====


== root ユーザ

Linux マシンの root ユーザには、ソースボリューム、デスティネーションボリューム、カタログボリュームをマウントする権限が付与されています。



== root 以外のユーザ

root 以外のユーザには、マウントされたボリュームに対する次の権限が与えられます。

* ソースボリュームへの読み取り権限アクセス
* マウントされたデスティネーションボリュームへの読み取り / 書き込み権限
* カタログボリュームへの読み取り / 書き込み権限

