---
sidebar: sidebar 
permalink: xcp-nfs-add-ons.html 
keywords: xcp, nfs, hdfs, connector, configure, security 
summary: XCP NFS アドオン機能は、 POSIX コネクタと HDFS コネクタの使用をサポートし、セキュリティを強化し、データ移行を高速化するスケールアウトアーキテクチャの使用をサポートしています。 
---
= XCP NFS アドオン機能
:allow-uri-read: 


[role="lead"]
XCP NFS アドオン機能は、 POSIX コネクタと HDFS コネクタの使用をサポートし、セキュリティを強化し、データ移行を高速化するスケールアウトアーキテクチャの使用をサポートしています。



== NFSv4 のサポート

データセンター内のソースボリューム、デスティネーションボリューム、カタログボリュームでのみ NFSv4 を有効にする場合は、エクスポートパスの代わりに POSIX パスを使用してデータを移行できます。POSIX パスを使用するには、まず XCP を実行しているホストシステムでソースボリューム、デスティネーションボリューム、カタログボリュームをマウントし、 POSIX ファイルパスを使用して XCP のソースボリュームとデスティネーションボリュームを指定する必要があります。を参照してください link:xcp-configure-posix-connector-nfs.html["POSIX コネクタを設定します"]。

[NOTE]
====
* NFSv4 のサポートは POSIX パスと「 copy 」操作に限定されており、「 sync 」操作はサポートされていません。
* XCP NFSv3 TCP ソケットクライアントエンジンと比較すると、 POSIX コネクタの速度が遅くなる可能性があります。


====


== POSIX コネクタ

XCPでは、POSIXコネクタを使用して、データ移行のソースパス、デスティネーションパス、およびカタログパスを提供できます。POSIXコネクタ（file：//）を使用すると、XCPはNFSv4、XFS、Veritasなど、Linuxでマウントされたすべてのファイルシステムにアクセスできます。root以外のユーザの場合、システム管理者はファイルシステムをマウントして、root以外のユーザがfile://プレフィックスを付けたPOSIXコネクタを使用してファイルシステムにアクセスできるようにすることができます。

ファイルをマウントするための十分な権限がない場合やデータセンターでのサポートが NFSv4 に制限されている場合は、 POSIX コネクタを使用すると便利です。このような場合、すべての root ユーザはソースとデスティネーションをマウントし、 POSIX コネクタを使用してパスにアクセスできます。POSIX コネクタを使用している場合は 'XCP COPY オペレーションのみを実行できます



== XCP セキュリティ

XCP セキュリティ機能を使用すると、 Linux ホストマシンで root 以外のユーザとして移行を実行できます。以前の XCP バージョンでは、 Linux マシンの root ユーザとして、ソース、デスティネーション、カタログボリュームのすべての権限を使用して移行を実行し、マウントは XCP 処理によって完了します。

データ移行を実行する前に、セキュリティをオフにして、管理者ができるだけ早くすべてをコピーできるようにするのが一般的です。XCP が数年使用されている本番環境での継続的な移行では、管理者（ root ）として実行するのは安全ではありません。そのため、 root ユーザとして XCP を実行する必要がある場合を削除すると、セキュアな環境で XCP を使用できるようになります。通常の root 以外のユーザが XCP 処理を実行する場合、 root 以外のユーザにはユーザと同じアクセス権と制限が与えられます。

このセキュアな環境では、 root ユーザがソース、デスティネーション、カタログのボリュームをホストマシンにマウントし、 root 以外のユーザがデータを書き込むために必要なデスティネーションボリュームとカタログボリュームに必要な権限を付与できます。これにより、 root 以外のユーザは XCP POSIX コネクタ機能を使用して移行を実行できます。



== XCP スケールアウト

これまでは、 XCP を使用したデータ移行は、 RAM と CPU が大きい単一のホストに限定されていました。移行を高速化するために、単一ホスト上のメモリとコアが増加しましたが、ペタバイト単位のデータのコピーにはかなりの時間がかかる可能性があります。XCP スケールアウトアーキテクチャでは、複数のホストを使用してデータを移行できます。この機能を使用すると、複数の Linux ホストを使用してワークロードを分散させ、マイグレーション時間を短縮できます。

単一システムのパフォーマンスでは不十分な環境では、マルチノードのスケールアウトを利用できます。1 つのノードのパフォーマンス制限を克服するには、単一の「 copy 」（または「 CAN-MD5 」）コマンドを使用して、複数の Linux システムまたは Hadoop クラスタノード上でワーカーを実行します。現在、 XCP スケールアウトは「 copy 」コマンド操作でのみサポートされています。



== Hadoop Distributed File System コネクタ

Hadoop Distributed File System （ HDFS ； Hadoop 分散ファイルシステム）ファイルシステムからネットアップファイルシステムへのデータの移行とその逆の移行がサポートされている XCP 。セキュリティが有効な Hadoop 環境では、 Hadoop クラスタの root 以外のユーザが NetApp NFSv4 エクスポートファイルシステムへの移行を実行できます。HDFS Connector （ HDFS ： // ）では、 XCP は、ベンダーが異なるすべての HDFS ファイルシステムにアクセスするための機能を提供します。root 以外のユーザは、 XCP を使用して、 HDFS または POSIX コネクタを使用した移行を実行できます。

HDFS クラスタは、複数のハイエンドの Linux マシンを使用する XCP スケールアウト構成に含めることができます。これにより、追加の XCP ワーカーノードに必要な量を最小限に抑えることができますデータ移行では、 HDFS クラスタノードを再利用するか、別々のホストに移動するかを選択できます。


NOTE: HDFS コネクタは MapR および Cloudera クラスタでサポートされますが、ベースラインの「コピー」操作のみを実行できます。
