---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: File Analytics for NFS をインストールまたはアップグレードします 
---
= File Analytics for NFS をインストールします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
File Analytics for NFS をインストールまたはアップグレードします。

NFS のシステム要件については、を参照してください link:xcp-install-xcp-nfs.html["XCP NFS をインストールします"]。「 configure.sh 」スクリプトは、 Linux サーバで利用可能な HTTPD および PostgreSQL のデフォルト設定をインストールし、有効にします。必要に応じて、より新しいバージョンに変更または更新したり、セキュリティガイドラインに従って更新したりできます。

.作業を開始する前に
* 同じホストで XCP アプリケーションと XCP サービスを同時に実行することはできません。実行中の XCP 処理がある場合は、設定を開始する前にその処理を実行します。
* Linux マシンが Yum リポジトリサーバまたはインターネットに接続されている必要があります。
* Linux マシンでファイアウォールが設定されている場合は、 XCP 、 XCP サービス、および XCP File Analytics で使用されるサービスで使用されるポートを有効にするようにファイアウォールの設定を変更する必要があります。詳細については、を参照してください xref:xcp-ports-used.html[XCP で使用されるポート]。


.手順
. XCP フォルダに移動し './configure.sh スクリプトを実行しますこのスクリプトは、 Linux マシンの設定と次のタスクの実行に 3 ～ 10 分かかります。
+
.. PostgreSQL パッケージをダウンロードします
.. PostgreSQL サーバをインストールします
.. HTTPD をインストールします
.. オープン SSL を使用して、自己署名証明書 (`erver.key および server.crt') を作成します。
.. XCP File Analytics データベースを作成します


. XCP 設定メニューから 'Option 1 Configure client system' を選択します
. 新規インストールの場合は、管理者ユーザとデータベースユーザのパスワードを更新します。アップグレードの場合は、 XCP サービスを停止するように求められます。終了したら 'Option 0' を選択します
. XCP サービスを開始します。次のコマンドを使用して、 XCP サービスが実行されているかどうかを確認します。 service XCP status
. ブラウザで File Analytics を起動します。 * 。 https://<ip address of Linux > /XCP * 。

