---
sidebar: sidebar 
permalink: xcp-nfs-reference-chmod.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFSコマンドリファレンス 
---
= chmod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS `chmod` コマンドは、指定されたディレクトリ構造のすべてのファイルのファイル権限をスキャンおよび変更します。「chmod」コマンドを使用するには、モードまたは参照、NFS共有、またはPOSIXパスを変数として指定する必要があります。XCP `chmod` コマンドは、指定されたパスの権限を再帰的に変更します。コマンドの出力には、スキャンされたファイルの合計数と、変更された権限が出力に表示されます。

.構文
[source, cli]
----
xcp chmod -mode <value> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode <IP address>:/source_vol

Xcp command : xcp chmod -mode <IP address>://source_vol
Stats : 6 scanned, 4 changed mode
Speed : 1.96 KiB in (2.13 KiB/s), 812 out (882/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux] #
----
====
次の表に、を示します `chmod` パラメータとその概要。

[cols="2*"]
|===
| パラメータ | 説明 


| <<nfs_chmod_exclude,chmod -exclude  filter>   | フィルタに一致するファイルとディレクトリを除外します。 


| <<nfs_chmod_match,chmod-match  >> | フィルタに一致するファイルとディレクトリのみを処理します。 


| <<nfs_chmod_reference,chmod -reference reference>  | 参照されるファイルまたはディレクトリポイントを指定します。 


| <<nfs_chmod_v,chmod -v >> | 処理されたすべてのオブジェクトの出力を報告します。 
|===


== chmod -exclude <filter>

を使用します `-exclude <filter>` パラメータと `chmod` フィルタに一致するファイルとディレクトリを除外するコマンド。

.構文
[source, cli]
----
xcp chmod -exclude <filter> -mode <value> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -exclude "fnm('3.img')" -mode 770 101.11.10.10:/s_v1/D3/

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chmod -exclude fnm('3.img') -mode 770 101.11.10.10:/s_v1/D3/
Stats : 5 scanned, 1 excluded, 5 changed mode
Speed : 2.10 KiB in (7.55 KiB/s), 976 out (3.43 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod-match <filter>

を使用します `-match <filter>` パラメータと `chmod` フィルタに一致するファイルとディレクトリのみを処理するコマンド。

.構文
[source, cli]
----
xcp chmod -match <filter>  -mode <value> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -match "fnm('2.img')" -mode 777 101.11.10.10:/s_v1/D2/

Filtered: 1 matched, 5 did not match
Xcp command : xcp chmod -match fnm('2.img') -mode 101.11.10.10:/s_v1/D2/
Stats : 6 scanned, 1 matched, 2 changed mode
Speed : 1.67 KiB in (1.99 KiB/s), 484 out (578/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]
----
====


== chmodリファレンス<reference>

を使用します `-reference <reference>` パラメータと `chmod` コマンドを使用して、参照されるファイルまたはディレクトリポイントを指定します。

.構文
[source, cli]
----
xcp chmod -reference <reference> <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/

Xcp command : xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/
Stats : 6 scanned, 6 changed mode
Speed : 3.11 KiB in (3.15 KiB/s), 1.98 KiB out (2.00 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== chmod -v

を使用します `-v` パラメータと `chmod` 処理されたすべてのオブジェクトの出力をレポートするコマンド。

.構文
[source, cli]
----
chmod -mode <value> -v <source NFS export path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode 111 -v file:///mnt/s_v1/D1/

mode of 'file:///mnt/s_v1/D1' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/1.txt' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_to_hardlink_1.img' changed from 0777 to 0111 mode
of 'file:///mnt/s_v1/D1/1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/hardlink_1.img' changed from 0777 to 0111 mode of
'file:///mnt/s_v1/D1/1.img1' changed from 0777 to 0111
Xcp command : xcp chmod -mode 111 -v file:///mnt/s_v1/D1/ Stats : 7 scanned, 7
changed mode
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====