---
sidebar: sidebar 
permalink: xcp-nfs-reference-scan.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFSコマンドリファレンス 
---
= スキャン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS `scan` コマンドは、ソースのNFSv3エクスポートパス全体を再帰的にスキャンし、ファイル構造の統計を返します。

NetAppでは、スキャン処理中にソースNFSエクスポートマウントを読み取り専用モードにすることを推奨しています。

.構文
[source, cli]
----
xcp scan <source_nfs_export_path>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan <IP address of NFS server>:/

source_vol
source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan <IP address of NFS server>:/source vol
----
====
次の表に、を示します `scan` パラメータとその概要。

[cols="2*"]
|===
| パラメータ | 説明 


| <<scan_l,スキャン-l>> | 長いリスト出力形式でファイルを一覧表示します。 


| <<scan_q,スキャン-q>> | スキャンされたファイルの数を表示します。 


| <<nfs_scan_stats_csv_html,スキャン統計>> | ツリー統計レポート形式のファイルを一覧表示します。 


| <<nfs_scan_stats_csv_html,スキャン- CSV>> | ツリー統計CSVレポート形式のファイルを一覧表示します。 


| <<nfs_scan_stats_csv_html,スキャン- HTML>> | ツリー統計HTMLレポート形式のファイルを一覧表示します。 


| <<名前のスキャン>> | ファイルリストとレポートからユーザ名とグループ名を除外します。 


| <<nfs_scan_newid,スキャン- NEWID >> | 新しいインデックスのカタログ名を指定します。 


| <<nfs_scan_id,scan-id  catalog_name >  | 前回のコピーまたはスキャンインデックスのカタログ名を指定します。 


| <<nfs_scan_match,スキャンマッチ >> | フィルタに一致するファイルとディレクトリのみを処理します。 


| <<nfs_scan_fmt,scan-fmt string_expression>  | は、の形式に一致するファイルとディレクトリのみを処理します。 


| <<nfs_scan_du,Scan-du>> | に、各ディレクトリ（サブディレクトリを含む）のスペース使用量をまとめます。 


| <<nfs_scan_md5,Scan-MD5 string_expression>  | ファイルにチェックサムを生成し、インデックス作成時にチェックサムを保存します（デフォルト：false）。 


| <<nfs_scan_depth,スキャン深度 >> | 検索の深さを制限します。 


| <<nfs_scan_dircount,scan-dircount[k]>  | ディレクトリを読み取るときの要求サイズを指定します。 


| <<nfs_scan_edupe,スキャン重複排除>> | 重複排除の見積もりをレポートに含めます。 


| <<nfs_scan_bs,Scan-bs[k]>  | を使用してデータを読み取るスキャンの読み取り/書き込みブロックサイズを指定します。 `-md5` または `-edupe` （デフォルト：64k）。 


| <<nfs_scan_parallel,スキャン-パラレル >> | 同時バッチプロセスの最大数を指定します（デフォルト：7）。 


| <<nfs_scan_noid,Scan-noId >> | デフォルトインデックスの作成をディセーブルにします（デフォルト：false）。 


| <<nfs_scan_subdir,scan-subdir-names>> | ディレクトリ内の最上位サブディレクトリの名前を取得します。 


| <<scan-preserve-atime>> | ソースで最後にアクセスした日付にすべてのファイルをリストアします。 


| <<-s3.insecureのスキャン>> | S3バケットの通信にHTTPSの代わりにHTTPを使用するオプションを提供します。 


| <<nfs_scan_endpoint,scan-s3.endpoint  >> | Amazon Web Services（AWS）エンドポイントのデフォルトのURLを、S3バケット通信用に指定したURLで上書きします。 


| <<nfs_scan_s3_profile,-s3.profileをスキャンします profile_name >  | S3バケットの通信用にAWSクレデンシャルファイルからプロファイルを指定します。 


| <<-s3.noverifyのスキャン>> | S3バケット通信のSSL証明書のデフォルトの検証を上書きします。 
|===


== スキャン-l

を使用します `-l` パラメータと `scan` コマンドを使用して、長いリスト出力形式でファイルを一覧表示します。

.構文
[source, cli]
----
xcp scan -l <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -l <IP address or hostname of NFSserver>:/source_vol

drwxr-xr-x --- root root 4KiB 4KiB 6s source_vol
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.1
drwxr-xr-x --- root root 4KiB 4KiB 42s source_vol/USER.2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42ssource_vol/USER.1/FILE_4
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.1/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_1
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_5
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_2
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_3
rw-r--r-- --- root root 1KiB 4KiB 42s source_vol/USER.2/FILE_4
Xcp command : xcp scan -l <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.89 KiB/s), 756 out (989/s)
Total Time : 0s.
STATUS : PASSED
----
====


== スキャン-q

を使用します `-q` パラメータと `scan` コマンドを実行して、スキャンされたファイル数を表示します。

.構文
[source, cli]
----
xcp scan -q <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -q <IP address or hostname of NFSserver>:/source_vol

Xcp command : xcp scan -q <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (3.96 KiB/s), 756 out(801/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan-stats、scan-csv、およびscan-html

を使用します `-stats`、 `-csv`および `-html` パラメータと `scan` ツリー統計レポート形式でファイルを一覧表示するコマンド。

[NOTE]
====
* を指定すると、 `-stats`オプション人間が判読可能なレポートがコンソールに出力されます。その他のレポート形式オプションは `-html`、または `-csv`です。カンマ区切り値（CSV）形式には正確な値があります。CSVレポートとHTMLレポートは、カタログが存在する場合は自動的にカタログに保存されます。
* XCPレポート（.csv、.html）は、ファイルで指定したカタログの場所に保存され `xcp.ini`ます。ファイルはフォルダに保存され `<catalog path>/catalog/indexes/1/reports`ます。サンプルレポートはで表示できますlink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886872["NetApp XCP 1.9.3リファレンス"^]。


====
.構文
[source, cli]
----
xcp scan -stats <ip_address>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -stats <ip_address>:/fg1

Job ID: Job_2023-11-23_23.23.33.930501_scan
== Maximum Values ==
Size Used Depth File Path Namelen Dirsize
50.4 MiB 50.6 MiB 1 24 20 33
== Average Values ==
Size Depth Namelen Dirsize
15.3 MiB 0 6 33
== Top Space Users ==
root
107 MiB
== Top File Owners ==
root
34
== Top File Extensions ==
.sh .out .py .sh1 other
8 2 2 1 20
16.0 KiB 3.09 MiB 448 1.48 KiB 502 MiB
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
20 1 2 10
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
76 KiB 12 KiB 5.16 MiB 102 MiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K

== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
34
== Accessed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
33
505 MiB
== Modified ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Changed ==
>1 year9-12 months 6-9 months 3-6 months 1-3 months 1-31 days 1-24 hrs <1 hour <15 mins
future
16
17
400 MiB 105
MiB
== Path ==
0-1024 >1024
33
Total count: 34
Directories: 1
Regular files: 33
Symbolic links: None
Special files: None
Hard links: None
Multilink files: None
Space Saved by Hard links (KB): 0
Sparse data: N/A
Dedupe estimate: N/A
Total space for regular files: size: 505 MiB, used: 107 MiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 8 KiB, used: 8 KiB
Total space used: 107 MiB
Xcp command : xcp scan -stats <ip_address>:/fg1
Stats : 34 scanned
Speed : 6.35 KiB in (7.23 KiB/s), 444 out (506/s)
Total Time : 0s.
Job ID : Job_2023-11-23_23.23.33.930501_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/
Job_2023-11-23_23.23.33.930501_scan.log

STATUS : PASSED
[root@client 1 linux]#


----
====
.構文
[source, cli]
----
xcp scan -csv <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -csv <IP address or hostname of NFS server>:/source_vol

scan <IP address or hostname of NFS server>:/source_vol
options,"{'-csv': True}"
summary,"13 scanned, 3.73 KiB in (11.3 KiB/s), 756 out (2.23 KiB/s), 0s."
Maximum Values,Size,Used,Depth,Namelen,Dirsize
Maximum Values,1024,4096,2,10,5
Average Values,Namelen,Size,Depth,Dirsize
Average Values,6,1024,1,4
Top Space Users,root
Top Space Users,53248
Top File Owners,root
Top File Owners,13
Top File Extensions,other
Top File Extensions,10
Number of files,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Number of files,0,10,0,0,0,0,0
Space used,empty,<8KiB,8-64KiB,64KiB-1MiB,1-10MiB,10-100MiB,>100MiB
Space used,0,40960,0,0,0,0,0
Directory entries,empty,1-10,10-100,100-1K,1K-10K,>10K
Directory entries,0,3,0,0,0,0
Depth,0-5,6-10,11-15,16-20,21-100,>100
Depth,13,0,0,0,0,0
Accessed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Accessed,0,0,0,0,0,10,0
Modified,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Modified,0,0,0,0,0,10,0
Changed,>1 year,>1 month,1-31 days,1-24 hrs,<1 hour,<15 mins,future
Changed,0,0,0,0,0,10,0

Total count,13
Directories,3
Regular files,10
Symbolic links,0
Special files,0
Hard links,0,
multilink files,0,
Space Saved by Hard links (KB),0
Sparse data,N/A
Dedupe estimate,N/A
Total space for regular files,size,10240,used,40960
Total space for symlinks,size,0,used,0
Total space for directories,size,12288,used,12288
Total space used,53248
Xcp command : xcp scan -csv <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (11.2 KiB/s), 756 out (2.22 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====
.構文
[source, cli]
----
xcp scan -html <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -html <IP address or hostname of NFS server>:/source_vol

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<html><head>
[redacted HTML contents]
</body></html>
Xcp command : xcp scan -html <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.31 KiB/s), 756 out(873/s)
Total Time : 0s.
STATUS : PASSED
[root@localhost source_vol]#
----
====


== 名前のスキャン

を使用します `-nonames` パラメータと `scan` ファイルリストまたはレポートからユーザ名とグループ名を除外するコマンド。


NOTE: と一緒に使用する場合 `scan` コマンドを入力します `-nonames` パラメータのみを使用して返される環境ファイルリスト `-l` オプション

.構文
[source, cli]
----
xcp scan -nonames <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -nonames <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -nonames <IP address or hostname of NFSserver>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 3.73 KiB in (4.66 KiB/s), 756 out(944/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-NEWID <name>

を使用します `-newid <name>` パラメータと `scan` スキャン実行時に新しいインデックスのカタログ名を指定するコマンド。

.構文
[source, cli]
----
xcp scan -newid <name> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol

Xcp command : xcp scan -newid ID001 <IP address or hostname of NFS server>:/source_vol
13 scanned, 0 matched, 0 error
Speed : 13.8 KiB in (17.7 KiB/s), 53.1 KiB out (68.0 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-id <catalog_name>

を使用します `-id` パラメータと `scan` 前のコピーまたはスキャンインデックスのカタログ名を指定するコマンド。

.構文
[source, cli]
----
xcp scan -id <catalog_name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -id 3

xcp: Index: {source: 10.10.1.10:/vol/ex_s01/etc/keymgr, target: None}
keymgr/root/cacert.pem
keymgr/cert/secureadmin.pem
keymgr/key/secureadmin.pem
keymgr/csr/secureadmin.pem
keymgr/root
keymgr/csr
keymgr/key
keymgr/cert
keymgr
9 reviewed, 11.4 KiB in (11.7 KiB/s), 1.33 KiB out (1.37 KiB/s), 0s.
----
====


== Scan-Match <filter>

を使用します `-match <filter>` パラメータと `scan` フィルタに一致するファイルとディレクトリのみが処理されるように指定するコマンド。

.構文
[source, cli]
----
xcp scan -match <filter> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -match bin <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Filtered: 0 did not match
Xcp command : xcp scan -match bin <IP address or hostname of NFSserver>:/source_vol
18 scanned, 18 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan-fmt <string_expression>

を使用します `-fmt` パラメータと `scan` 指定した形式に一致するファイルとディレクトリのみが返されるように指定するコマンド。

.構文
[source, cli]
----
xcp scan -fmt <string_expression> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -fmt "'{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime)"
<IP address or hostname of NFS server>:/source_vol

source_vol, <IP address or hostname of NFS server>:/source_vol, 1583294484.46, 1583294492.63,
1583294484.46
ILE_1, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_1, 1583293637.88,
1583293637.83, 1583293637.83
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_2, 1583293637.88,
1583293637.83, 1583293637.84
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_3, 1583293637.88,
1583293637.84, 1583293637.84
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_4, 1583293637.88,
1583293637.84, 1583293637.84
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.1/FILE_5, 1583293637.88,
1583293637.84, 1583293637.84
file1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file1.txt, 1583294284.78,
1583294284.78, 1583294284.78
file2.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/file2.txt, 1583294284.78,
1583294284.78, 1583294284.78
logfile.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/logfile.txt,
1583294295.79, 1583294295.79, 1583294295.79
log1.txt, <IP address or hostname of NFS server>:/source_vol/USER.1/log1.txt, 1583294295.8,
1583294295.8, 1583294295.8
r1.txt, <IP address or hostname of NFS server>:/source_vol/r1.txt, 1583294484.46, 1583294484.45,
1583294484.45
USER.1, <IP address or hostname of NFS server>:/source_vol/USER.1, 1583294295.8, 1583294492.63,
1583294295.8
USER.2, <IP address or hostname of NFS server>:/source_vol/USER.2, 1583293637.95, 1583294492.63,
1583293637.95
FILE_1, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_1, 1583293637.95,
1583293637.94, 1583293637.94
FILE_5, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_5, 1583293637.96,
1583293637.94, 1583293637.94
FILE_2, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_2, 1583293637.96,
1583293637.95, 1583293637.95
FILE_3, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_3, 1583293637.96,
1583293637.95, 1583293637.95
FILE_4, <IP address or hostname of NFS server>:/source_vol/USER.2/FILE_4, 1583293637.96,
1583293637.95, 1583293637.96
Xcp command : xcp scan -fmt '{}, {}, {}, {}, {}'.format(name, x, ctime, atime, mtime) <IP address
or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (4.14 KiB/s), 756 out (683/s)
Total Time : 1s.
STATUS : PASSED
----
====


== Scan-du

を使用します `-du` パラメータと `scan` 各ディレクトリ（サブディレクトリを含む）のスペース使用量を要約するコマンド。

.構文
[source, cli]
----
xcp scan -du <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -du <IP address or hostname of NFSserver>:/source_vol

24KiB source_vol/USER.1
24KiB source_vol/USER.2
52KiB source_vol
Xcp command : xcp scan -du <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (12.9 KiB/s), 756 out (2.07KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== スキャン- MD5 <string_expression>

を使用します `-md5` パラメータと `scan` ファイルリストのチェックサムを生成し、インデックス作成時にチェックサムを保存するコマンド。デフォルト値はfalseに設定されています。


NOTE: チェックサムはファイルの検証には使用されず、スキャン処理中のファイルリストにのみ使用されます。

.構文
[source, cli]
----
xcp scan -md5 <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -md5 <IP address or hostname of NFSserver>:/source_vol

source_vol
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_4
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.1/FILE_5
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file1.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/file2.txt
d41d8cd98f00b204e9800998ecf8427esource_vol/USER.1/logfile.txt
d41d8cd98f00b204e9800998ecf8427e source_vol/USER.1/log1.txt
e894f2344aaa92289fb57bc8f597ffa9 source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_1
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_5
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_2
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_3
d47b127bc2de2d687ddc82dac354c415 source_vol/USER.2/FILE_4
Xcp command : xcp scan -md5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (34.5 KiB/s), 2.29 KiB out (4.92 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-depth <n>

を使用します `-depth <n>` パラメータと `scan` スキャンの検索深度を制限するコマンド。。 `-depth <n>` パラメータは、XCPがファイルをスキャンできるサブディレクトリの深さを指定します。たとえば、番号2が指定されている場合、XCPは最初の2つのサブディレクトリレベルのみをスキャンします。

.構文
[source, cli]
----
xcp scan -depth <n> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -depth 2 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -depth 2 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (6.94 KiB/s), 756 out (1.12KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-dircount <n[k]>

を使用します `-dircount <n[k]>` パラメータと `scan` コマンドを使用して、スキャンでディレクトリを読み取るときの要求サイズを指定します。デフォルト値は64kです。

.構文
[source, cli]
----
xcp scan -dircount <n[k]> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -dircount 64k <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
----
====


== スキャン重複排除

を使用します `-edupe` パラメータと `scan` 重複排除の見積もりをレポートに含めるコマンド。


NOTE: Simple Storage Service（S3）ではスパースファイルはサポートされません。そのため、ターゲットデスティネーションとしてS3バケットを指定 `scan -edupe` スパースデータの場合は値"None"を返します。

.構文
[source, cli]
----
xcp scan -edupe <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
root@localhost linux]# ./xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol

== Maximum Values ==
Size Used Depth Namelen Dirsize
1 KiB 4 KiB 2 11 9
== Average Values ==
Namelen Size Depth Dirsize
6 682 1 5
== Top Space Users ==
root
52 KiB
== Top File Owners ==
root
18
== Top File Extensions ==
.txt other
5 10
== Number of files ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
    4 11
== Space used ==
empty <8KiB 8-64KiB 64KiB-1MiB 1-10MiB 10-100MiB >100MiB
40 KiB
== Directory entries ==
empty 1-10 10-100 100-1K 1K-10K >10K
3
== Depth ==
0-5 6-10 11-15 16-20 21-100 >100
18
== Accessed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour
4
<15 mins
11
future
== Modified ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
15
== Changed ==
>1 year >1 month 1-31 days 1-24 hrs <1 hour <15 mins future
                                     15
Total count: 18
Directories: 3
Regular files: 15
Symbolic links: None
Special files: None
Hard links: None,
multilink files: None,
Space Saved by Hard links (KB): 0
Sparse data: None
Dedupe estimate: N/A
Total space for regular files: size: 10.0 KiB, used: 40 KiB
Total space for symlinks: size: 0, used: 0
Total space for directories: size: 12 KiB, used: 12 KiB
Total space used: 52 KiB
Xcp command : xcp scan -edupe <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 16.0 KiB in (52.7 KiB/s), 2.29 KiB out (7.52 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-BS <n[k]>

を使用します `-bs <n[k]>` パラメータと `scan` 読み取り/書き込みブロックサイズを指定するコマンド。この環境は、を使用してデータを読み取るスキャンを実行します。 `-md5` または `-edupe` パラメータデフォルトのブロックサイズは64kです。

.構文
[source, cli]
----
xcp scan -bs <n[k]> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -bs 32 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -bs 32 <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (19.0 KiB/s), 756 out (3.06KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-parallel <n>

を使用します `-parallel` パラメータと `scan` コマンドを使用して、同時バッチプロセスの最大数を指定します。デフォルト値は7です。

.構文
[source, cli]
----
xcp scan -parallel <n> <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -parallel 5 <IP address or hostname of NFS server>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (7.36 KiB/s), 756 out (1.19 KiB/s)
Total Time : 0s.
STATUS : PASSED
----
====


== Scan-noId

を使用します `-noId` パラメータと `scan` デフォルトインデックスの作成を無効にするコマンド。デフォルト値は false です。

.構文
[source, cli]
----
xcp scan -noId <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -noId <IP address or hostname of NFS server>:/source_vol

source_vol
source_vol/USER.1/FILE_1
source_vol/USER.1/FILE_2
source_vol/USER.1/FILE_3
source_vol/USER.1/FILE_4
source_vol/USER.1/FILE_5
source_vol/USER.1/file1.txt
source_vol/USER.1/file2.txt
source_vol/USER.1/logfile.txt
source_vol/USER.1/log1.txt
source_vol/r1.txt
source_vol/USER.1
source_vol/USER.2
source_vol/USER.2/FILE_1
source_vol/USER.2/FILE_5
source_vol/USER.2/FILE_2
source_vol/USER.2/FILE_3
source_vol/USER.2/FILE_4
Xcp command : xcp scan -noId <IP address or hostname of NFSserver>:/source_vol
18 scanned, 0 matched, 0 error
Speed : 4.59 KiB in (5.84 KiB/s), 756 out(963/s)
Total Time : 0s.
STATUS : PASSED
----
====


== scan-subdir-names

を使用します `-subdir-names` パラメータと `scan` コマンドを使用して、ディレクトリ内の最上位サブディレクトリの名前を取得します。

.構文
[source, cli]
----
xcp scan -subdir-names <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@localhost linux]# ./xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol

source_vol
Xcp command : xcp scan -subdir-names <IP address or hostname of NFS server>:/source_vol
7 scanned, 0 matched, 0 error
Speed : 1.30 KiB in (1.21 KiB/s), 444 out(414/s)
Total Time : 1s.
STATUS : PASSED
----
====


== scan-preserve-atime

を使用します `-preserve-atime` パラメータと `scan` ソースで最後にアクセスした日付にすべてのファイルをリストアするコマンド。

読み取り時にアクセス時間を変更するようにストレージシステムが設定されている場合、NFS共有のスキャン時にファイルのアクセス時間が変更されます。XCPはアクセス時間を直接変更しません。XCPはファイルを1つずつ読み取り、アクセス時間の更新をトリガーします。。 `-preserve-atime` オプションを選択すると、XCP読み取り操作の前に設定された元の値にアクセス時間がリセットされます。

.構文
[source, cli]
----
xcp scan -preserve-atime <ip_address_or_hostname>:/source_vol
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client 1 linux]# ./xcp scan -preserve-atime 101.10.10.10:/source_vol

xcp: Job ID: Job_2022-06-30_14.14.15.334173_scan
source_vol/USER2/DIR1_4/FILE_DIR1_4_1024_1
source_vol/USER2/DIR1_4/FILE_DIR1_4_13926_4
source_vol/USER2/DIR1_4/FILE_DIR1_4_65536_2
source_vol/USER2/DIR1_4/FILE_DIR1_4_7475_3
source_vol/USER2/DIR1_4/FILE_DIR1_4_20377_5
source_vol/USER2/DIR1_4/FILE_DIR1_4_26828_6
source_vol/USER2/DIR1_4/FILE_DIR1_4_33279_7
source_vol/USER2/DIR1_4/FILE_DIR1_4_39730_8
source_vol/USER1
source_vol/USER2
source_vol/USER1/FILE_USER1_1024_1
source_vol/USER1/FILE_USER1_65536_2
source_vol/USER1/FILE_USER1_7475_3
source_vol/USER1/FILE_USER1_13926_4
source_vol/USER1/FILE_USER1_20377_5
source_vol/USER1/FILE_USER1_26828_6
source_vol/USER1/FILE_USER1_33279_7
source_vol/USER1/FILE_USER1_39730_8
source_vol/USER1/DIR1_2
source_vol/USER1/DIR1_3
source_vol/USER2/FILE_USER2_1024_1
source_vol/USER2/FILE_USER2_65536_2
source_vol/USER2/FILE_USER2_7475_3
source_vol/USER2/FILE_USER2_13926_4
source_vol/USER2/FILE_USER2_20377_5
source_vol/USER2/FILE_USER2_26828_6
source_vol/USER2/FILE_USER2_33279_7
source_vol/USER2/FILE_USER2_39730_8
source_vol/USER2/DIR1_3
source_vol/USER2/DIR1_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_1024_1
source_vol/USER1/DIR1_2/FILE_DIR1_2_7475_3
source_vol/USER1/DIR1_2/FILE_DIR1_2_33279_7
source_vol/USER1/DIR1_2/FILE_DIR1_2_26828_6
source_vol/USER1/DIR1_2/FILE_DIR1_2_65536_2
source_vol/USER1/DIR1_2/FILE_DIR1_2_39730_8
source_vol/USER1/DIR1_2/FILE_DIR1_2_13926_4
source_vol/USER1/DIR1_2/FILE_DIR1_2_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER1/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER1/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER1/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER1/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER1/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER1/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER1/DIR1_3/FILE_DIR1_3_39730_8
source_vol/USER2/DIR1_3/FILE_DIR1_3_1024_1
source_vol/USER2/DIR1_3/FILE_DIR1_3_65536_2
source_vol/USER2/DIR1_3/FILE_DIR1_3_7475_3
source_vol/USER2/DIR1_3/FILE_DIR1_3_13926_4
source_vol/USER2/DIR1_3/FILE_DIR1_3_20377_5
source_vol/USER2/DIR1_3/FILE_DIR1_3_26828_6
source_vol/USER2/DIR1_3/FILE_DIR1_3_33279_7
source_vol/USER2/DIR1_3/FILE_DIR1_3_39730_8
source_vol
Xcp command : xcp scan -preserve-atime 101.10.10.10:/source_vol
Stats : 55 scanned
Speed : 14.1 KiB in (21.2 KiB/s), 2.33 KiB out (3.51 KiB/s)
Total Time : 0s.
Job ID : Job_2022-06-30_14.14.15.334173_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2022-06-30_14.14.15.334173_scan.log
STATUS : PASSED
----
====


== -s3.insecureのスキャン

を使用します `-s3.insecure` パラメータと `scan` S3バケットの通信にHTTPSではなくHTTPを使用するコマンド。

.構文
[source, cli]
----
xcp scan -s3.insecure s3://<bucket_name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.insecure s3://bucket1

Job ID: Job_2023-06-08_08.16.31.345201_scan
file5g_1
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.insecure s3:// -bucket1
Stats : 8 scanned, 6 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-08_08.16.31.345201_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.16.31.345201_scan.log
STATUS : PASSED
----
====


== scan-s3.endpoint <s3_endpoint_url>

を使用します `-s3.endpoint <s3_endpoint_url>` パラメータと `scan` AWSエンドポイントのデフォルトのURLをS3バケットの通信用に指定したURLで上書きするコマンド。

.構文
[source, cli]
----
xcp scan -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing

Job ID: Job_2023-06-13_11.23.06.029137_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.endpoint https://<endpoint_url>: s3://xcp-testing
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
Job ID : Job_2023-06-13_11.23.06.029137_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.23.06.029137_scan.log
STATUS : PASSED
----
====


== -s3.profile <name>のスキャン

を使用します `s3.profile` パラメータと `scan` S3バケット通信用のAWSクレデンシャルファイルからプロファイルを指定するコマンド。

.構文
[source, cli]
----
xcp scan -s3.profile <name> -s3.endpoint https://<endpoint_url>: s3://<bucket_name>
----
.例を示します
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>:
s3://bucket1

Job ID: Job_2023-06-08_08.47.11.963479_scan
1 scanned, 0 in (0/s), 0 out (0/s), 5s
USER1/FILE_USER1_1024_1
USER1/FILE_USER1_1024_2
USER1/FILE_USER1_1024_3
USER1/FILE_USER1_1024_4
USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.profile sg -s3.endpoint https://<endpoint_url>: s3://bucket1
Stats : 7 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 6s.
Job ID : Job_2023-06-08_08.47.11.963479_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-08_08.47.11.963479_scan.log
STATUS : PASSED
[root@client1 linux]#
----
====


== -s3.noverifyのスキャン

を使用します `-s3.noverify` パラメータと `scan` コマンドを使用して、S3バケットの通信用のSSL証明書のデフォルトの検証を無視します。

.構文
[source, cli]
----
xcp scan -s3.noverify s3://<bucket_name>
----
.例を示します
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp scan -s3.noverify s3:// bucket1

Job ID: Job_2023-06-13_11.00.59.742237_scan
aws_files/USER1/FILE_USER1_1024_1
aws_files/USER1/FILE_USER1_1024_2
aws_files/USER1/FILE_USER1_1024_3
aws_files/USER1/FILE_USER1_1024_4
aws_files/USER1/FILE_USER1_1024_5
Xcp command : xcp scan -s3.noverify s3://bucket1
Stats : 8 scanned, 5 s3.objects
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 2s.
Job ID : Job_2023-06-13_11.00.59.742237_scan
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-06-13_11.00.59.742237_scan.log
STATUS : PASSED
----
====