---
sidebar: sidebar 
permalink: xcp-prepare-linux-for-xcp-nfs.html 
keywords: netapp, xcp, prepare, preparing, preparation, linux, nfs, configure, configuring, catalog, storage, 
summary: XCP NFS 用 Linux を準備します 
---
= XCP NFS 用 Linux を準備します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP NFS は、 Linux クライアントホストシステムを使用して並列 I/O ストリームを生成し、使用可能なネットワークとストレージのパフォーマンスを最大限に活用します。



=== カタログを構成します

XCP は、 NFSv3 からアクセス可能なカタログディレクトリに処理レポートとメタデータを保存します。カタログのプロビジョニングは、インストール前に次のタスクを必要とする 1 回限りのタスクです。

* セキュリティと信頼性を確保するための NetApp NFSv3 エクスポート。
* エクスポートを含むアグリゲートに 10 本以上のディスクまたはソリッドステートドライブが含まれていること。
* XCP の実行に使用されるすべての Linux クライアントの IP アドレスについて、カタログエクスポートへのルートアクセスを許可するように構成されたストレージ（複数の XCP クライアントでカタログの場所を共有可能）。
* インデックスを作成するオブジェクト（ディレクトリとファイル、ハードリンク） 1 、 000 万個ごとに約 1GB のスペースが必要です。再開または同期できるコピーごと、およびオフラインで検索可能なスキャンごとにインデックスが必要です。



NOTE: XCP カタログは別途保存する必要があります。これらのディレクトリは、ソースまたはデスティネーションの NFS エクスポートディレクトリには配置しないでください。XCP はメタデータを管理します。このレポートは、初期セットアップで指定したカタログの場所に保存されます。XCP を使用して処理を実行する前に、レポートの格納場所を指定して更新する必要があります。



=== ストレージを設定する

XCP NFS の移行および移行には、ソースとターゲットのストレージに関する次の要件があります。

* ソースサーバとターゲットサーバで NFSv3 プロトコルサービスが有効になっている必要があります。NFSv4 ACL を移行する場合は、デスティネーションサーバで NFSv4 プロトコルサービスと NFSv4 ACL を有効にする必要があります。
* ソースボリュームとターゲットボリュームは、 XCP Linux クライアントホストへの「 root 」アクセスでエクスポートされる必要があります。



NOTE: 管理者が誤って変更できないように、 NFSv3 および NFSv4 エクスポートのソースを読み取り専用として設定してください。
