---
sidebar: sidebar 
permalink: xcp-smb-reference-copy.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: XCP SMB「copy」コマンドリファレンス 
---
= コピー
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
。 `copy` コマンドは、ソースディレクトリ構造全体をスキャンし、デスティネーションSMB共有にコピーします。。 `copy` コマンドには、ソースパスとデスティネーションパスが変数として必要です。スキャンおよびコピーされたファイル、スループット / 速度、および経過時間の詳細が、 5 秒ごとにコンソールに出力されます。

[NOTE]
====
* ランタイムログファイルは「C：\NetApp\XCP」に格納されます。
* これ `copy` コマンドは、Access Control List（ACL；アクセス制御リスト）を使用せずにデータをコピーします。


====
.構文
[source, cli]
----
xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====
次の表に、を示します `copy` パラメータとその概要。

[cols="2*"]
|===
| パラメータ | 説明 


| <<smb_copy_help,copy -h、--help>> | に関する詳細情報を表示します。 `copy` コマンドを実行します 


| <<コピー-v>> | デバッグの冗長性を高めます。 


| <<smb_copy_parallel,コピーパラレル >> | 同時処理プロセスの数を指定します（デフォルト：<cpu-count>）。 


| <<smb_copy_match,コピーマッチ >> | フィルタに一致するファイルとディレクトリのみを処理します（ `xcp help - match` を参照してください）。 


| <<smb_copy_exclude,コピー-除外 >> | フィルタ内のファイルとディレクトリのみを除外します。 


| <<copy-preserve-atime>> | ソースに最終アクセス日をリストアします。 


| <<smb_copy_acl,コピーACL>> | セキュリティ情報をコピーします。 


| <<smb_copy_acl,copy-fallback-user fallback_user>  | ローカル（ドメインでない）ソースマシンユーザーの権限を受け取るターゲットマシン上のActive Directoryユーザーまたはローカル（ドメインでない）ユーザーを指定します。たとえば、domain\administratorのように指定します。 


| <<smb_copy_acl,copy-fallback-group fallback_group>  | ローカル（非ドメイン）ソースマシングループの権限を受け取るターゲットマシン上のActive Directoryグループまたはローカル（非ドメイン）グループを指定します。たとえば、domain\administratorsなどです。 


| <<smb_copy_root,copy-root>> | ルートディレクトリのACLをコピーします。 


| <<smb_copy_aclverify,copy-aclverify｛yes、no｝>> | copy-acl処理中にACL検証をスキップまたは含めるオプションを提供します。 


| <<copy-noownership>> | 所有権はコピーされません。 


| <<smb_copy_bs,コピー-BS >> | 読み取り/書き込みブロックサイズ（デフォルト：1M） 


| <<コピー広告>> | NTFS代替データストリームをソースSMB共有からデスティネーションSMB共有にコピーします。 
|===


== copy -h、--help

を使用します `-h` および `–-help` パラメータと `copy` コマンドを使用して `copy` コマンドを実行します

.構文
[source, cli]
----
xcp copy –help
----
.例を示します
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp copy –help

usage: xcp copy [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve- atime] [-acl] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-root] [-noownership] [- aclverify {yes,no}] [-bs <n>] [-ads]
         source target

positional arguments:
   source
   target

optional arguments:
-h, --help            show this help message and exit
-v                    increase debug verbosity
-parallel <n>         number of concurrent processes (default: <cpu-count>)
-match <filter>       only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>     Exclude files and directories that match the filter (see `xcp help - exclude` for details)
-preserve-atime       restore last accessed date on source
-acl                  copy security information
-fallback-user FALLBACK_USER
                      the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                      the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
-loglevel <name>      option to set log level filter (default:INFO)
-root                 copy acl for root directory
-noownership          do not copy ownership
-aclverify {yes,no}   choose whether you need to skip acl verification
-bs <n>               read/write block size for copy (default: 1M)
-ads                  copy NTFS alternate data streams.
----
====


== コピー-v

を使用します `-v` パラメータと `copy` 詳細なデバッグ情報を提供するコマンド。

.構文
[source, cli]
----
xcp copy -v \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1

failed to set attributes for "d1": (5, 'CreateDirectory', 'Access is denied.')
failed to copy "f1.txt": (5, 'CreateFile', 'Access is denied.')
failed to set attributes for "": (5, 'SetFileAttributesW', 'Access is denied.') error setting timestamps on "": errno (code: 5) Access is denied.
H:\p 4\xcp_latest\xcp_cifs\xcp\ main .py copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1
3 scanned, 0 matched, 0 skipped, 1 copied, 0 (0/s), 3 errors
Total Time : 3s
STATUS : FAILED
----
====


== コピーパラレル<n>

を使用します `-parallel <n>` パラメータと `copy` コマンドを使用して、XCP同時プロセスの数を増減します。のデフォルト値 `-parallel` はCPU数と同じです。


NOTE: nの最大値は61です。

.構文
[source, cli]
----
xcp copy -parallel <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -parallel 7	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -parallel 7 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0errors
Total Time : 2s
STATUS : PASSED
----
====


== Copy-Match <filter>

を使用します `-match <filter>` パラメータと `copy` 渡された引数に一致するデータのみをコピーするコマンド。

.構文
[source, cli]
----
xcp copy -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 5 matched, 4 copied, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== Copy-Exclude <filter>

を使用します `-exclude <filter>` パラメータと `copy` 除外されたデータのみをコピーするコマンド。

.構文
[source, cli]
----
xcp copy -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
次の例では、名前に「resync」という文字列が含まれているファイルおよびディレクトリがコピー対象から除外されています。

.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -exclude "'resync' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address or hostname of SMB server>\dest_share


xcp copy -exclude 'resync' in name \\<IP address or hostname of SMB server>\source_share \\\\<IP address or hostname of SMB server>\dest_share
18 scanned, 2 excluded, 0 skipped, 15 copied, 122KiB (50.5KiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy-preserve-atime

を使用します `-preserve-atime` パラメータと `copy` XCPがファイルを読み取る前に「atime」を元の値にリセットするコマンド。

.構文
[source, cli]
----
xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== copy-acl-fallback-user <fallback_user>-fallback-group <fallback_group>

を使用します `-acl` パラメータと `copy` セキュリティ記述子（ACL）の転送をアクティブにするコマンド。

を使用します `-acl` パラメータと `-fallback-user` および `-fallback-group` ターゲットマシン上のユーザーとグループを指定するか、Active Directoryからローカル(ドメインではない)ソースマシンのユーザーまたはグループの権限を取得するオプション。これは、Active Directoryの一致しないユーザを指しているわけではありません。

.構文
[source, cli]
----
xcp copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----


== copy-aclverify｛yes、no｝

を使用します `-aclverify {yes,no}` パラメータと `copy` ACLコピー処理中にACL検証をスキップまたは含めるオプションを指定するコマンド。

を使用する必要があります `-aclverify {yes,no}` パラメータと `copy -acl` コマンドを実行しますデフォルトでは、ACLコピー操作によってACLが検証されます。を設定した場合は `-aclverify` オプションをに設定します `no`を使用すると、ACLの検証を省略して、 `fallback-user` および `fallback-group` オプションは必須ではありません。設定した場合 `-aclverify` 終了： `yes`を使用するには、 `fallback-user` および `fallback-group` 次の例に示すように、オプションを指定します。

.構文
[source, cli]
----
xcp copy -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group"
\\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 15s, 0 acls copied xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (634/s), 0 errors, 11 acls copied
Total Time : 16s
STATUS : PASSED

C:\NetApp\xcp>xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (5.61KiB/s), 0 errors, 11 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copy-root

を使用します `-root` パラメータと `copy` ルートディレクトリのACLをコピーするコマンド。

.構文
[source, cli]
----
xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 200 (108/s), 0 errors, 6 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== copy-noownership

を使用します `-noownership` パラメータと `copy` ソースからデスティネーションに所有権をコピーしないように指定するコマンド。を使用する必要があります `-noownership` を使用 `-acl` 必要なオプション `fallback-user` および `fallback-group` （必須パラメータとして）。

.構文
[source, cli]
----
xcp.exe copy -acl -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 135 copied, 4.26MiB (872KiB/s), 0 errors, 15s, 137 acls copied xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (1.01MiB/s), 0 errors, 567 acls copied
Total Time : 17s
STATUS : PASSED
----
====


== コピーBS <n>

を使用します `-bs <n>` パラメータと `copy` 読み取り/書き込みブロックサイズを指定するコマンド。デフォルト値は1Mです。

.構文
[source, cli]
----
xcp.exe copy -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\Netapp\xcp>xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (6.75MiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== コピー広告

を使用します `-ads` パラメータと `copy` NTFS代替データストリームをソースSMB共有からデスティネーションSMB共有にコピーするコマンド。

.構文
[source, cli]
----
xcp copy -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.例を示します
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

6   scanned, 0 matched, 0 skipped, 3 copied, 13 (2.41/s), 0 errors, 5s, 10 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	10s, 11 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	15s, 12 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	20s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	25s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	30s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	35s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	40s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	45s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	2m15s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	3m5s, 13 ads copied
xcp copy -ads \\<source_IP_address>\source_share\src \\<desination_IP_address>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 26 (0.137/s), 0 errors, 14 ads copied
Total Time : 3m9s
STATUS : PASSED
----
====