---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: POSIX コネクタを使用すると、 XCP は NFSv4 、 XFS 、 Veritas など、 Linux でマウントされた任意のファイルシステムにアクセスできます。 
---
= 同じXCPホストで複数のXCPジョブを実行します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP 1.9.2以降では、各ジョブに十分なリソースがホストにある場合は、1つのXCPホストで複数のXCPジョブまたはコマンドを実行できます。複数のジョブをサポートするコマンドを実行すると、XCPは最小限のホストメモリを使用してジョブを完了します。これにより、同じホスト構成で追加のジョブを実行するための容量が作成されます。



== 最小システム要件

XCPジョブごとに、中規模から大規模の移行用に、最大64GBのホストメモリと8コアを割り当てる必要があります。


NOTE: SMBデータの移行では、同じホストで複数のXCPジョブを実行することはサポートされていません。



== ロギング

デフォルトでは、各XCPジョブは、ジョブIDに固有の個別のログファイルに記録されます。このロギングメカニズムは、同じホストで複数のジョブを実行する場合に適しています。NetAppでは、の変更は推奨していません `xcpLogConfig.Json` 単一のを使用するファイル `xcp.log` 同じホストで並行して実行されている複数のXCPジョブをログに記録するファイル。



== サポートされるコマンド

同じホストで複数のXCPジョブを実行するには、次のXCPコマンドを使用します。

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== サポートされないコマンドです

では、同じホストで複数のXCPジョブを実行することはサポートされていません。 `sync` コマンドを実行します
